library(openintro)
data(mammals)
head(mammals)
# use code in hw5 explanation for building mammal2 dataset
mammals2 <- mammals[rowSums(is.na(mammals)) == 0,]
see if loaded correct datasets
head(mammals)
head(mammals2)
# less obs. in mammals2, successfully exclude all NA rows
# check for variable types before plotting
sapply(mammals2, class)
# all variables are nicely fall in each type
# all variable names are self-explanable, no need for renaming, just need to pay attention to the units in comprehension.
plot(mammals2)
savehistory('hw5codedraft')
savehistory('hw5codedraft.R')
# Try other methods
install.packages('GGally')
library(GGally)
ggpairs(mammals2)
ggpairs(mammals2,cardinality_threshold = 63)
model1 <- lm(TotalSleep ~ BodyWt + BrainWt + LifeSpan + Gestation + Predation + Exposure + Danger,data = mammals2)
summary(model1)
model1.1 <- lm(TotalSleep ~ Gestation + Predation + Danger,data = mammals2)
summary(model1.1)
plot(model1)
plot(model1.1)
sapply(mammals2, class)
# Get ready to convert the type of the last three variables to be 'factor' - categorical
mammals2.1 <- mammals2
convert <- function(obj,types){
for (i in 1:length(obj)){
FUN <- switch(types[i],character = as.character,
numeric = as.numeric,
factor = as.factor, date = as.Date, time = time)
obj[,i] <- FUN(obj[,i])
}
obj
}
numcol = dim(data)[2]
type.target = rep("numeric", numcol)
type.target[c(1:numcol)[names(data) == "Species"]] <- "factor"
type.target[c(1:numcol)[names(data) == "Predation"]] <- "factor"
type.target[c(1:numcol)[names(data) == "Exposure"]] <- "factor"
type.target[c(1:numcol)[names(data) == "Danger"]] <- "factor"
numcol = dim(mammals2.1)[2]
type.target = rep("numeric", numcol)
type.target[c(1:numcol)[names(data) == "Species"]] <- "factor"
type.target[c(1:numcol)[names(data) == "Predation"]] <- "factor"
type.target[c(1:numcol)[names(data) == "Exposure"]] <- "factor"
type.target[c(1:numcol)[names(data) == "Danger"]] <- "factor"
cbind(names(mammals2.1), type.target)
mammals2.1 <- convert(mammals2.1, type.target)
sapply(mammals2.1,class)
numcol = dim(mammals2.1)[2]
type.target = rep("numeric", numcol)
type.target[c(1:numcol)[names(mammals2.1) == "Species"]] <- "factor"
type.target[c(1:numcol)[names(mammals2.1) == "Predation"]] <- "factor"
type.target[c(1:numcol)[names(mammals2.1) == "Exposure"]] <- "factor"
type.target[c(1:numcol)[names(mammals2.1) == "Danger"]] <- "factor"
cbind(names(mammals2.1), type.target)
mammals2.1 <- convert(mammals2.1, type.target)
sapply(mammals2.1,class)
# Finished converting the type
# see model 2 for regression
model2 <- lm(TotalSleep ~ BodyWt + BrainWt + LifeSpan + Gestation + Predation + Exposure + Danger,data = mammals2.1)
summary(model2)
par(mfrow(2,2))
par(mfrow = c(2,2))
plot(model3)
plot(model2)
plot(model1)
plot(model1.1)
install.packages('MASS')
library(MAA)
library(MASS)
step <- stepAIC (model1.AIC, direction="both")
model1.AIC<- lm( TotalSleep ~ BodyWt + BrainWt + LifeSpan + Gestation + Predation + Exposure + Danger,data = mammals2 )
step <- stepAIC (model1.AIC, direction="both")
savehistory('hw5-codedraft2.R')
model1.AIC <- stepAIC(model1)
model2.AIC <- stepAIC(model2)
View(model1)
View(model2)
View(step)
summary(model2)
View(model1.AIC)
View(model2.AIC)
summary(model1.AIC)
summary(model2.AIC)
summary(model1.1)
modelbonus <- lm(TotalSleep ~ 1/BodyWt + 1/BrainWt + 1/LifeSpan + 1/Gestation + 1/Predation + 1/Exposure + 1/Danger,data = mammals2.1)
summary(modelbonus)
model2 <- lm(TotalSleep ~ 1(BodyWt + BrainWt + LifeSpan + Gestation + Predation + Exposure + Danger),data = mammals2.1)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt) + I(1/BrainWt) + I(1/LifeSpan) + I(1/Gestation) + I(1/Predation) + I(1/Exposure) + I(1/Danger),data = mammals2.1)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt) + I(1/BrainWt) + I(1/LifeSpan) + I(1/Gestation) + I(Predation) + I(Exposure) + I(Danger),data = mammals2.1)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt) + I(1/BrainWt) + I(1/LifeSpan) + I(1/Gestation) + I(Predation) + I(Exposure) + I(Danger),data = mammals2)
summary(modelbonus)
summary(model2)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt) + I(1/BrainWt) + I(1/LifeSpan) + I(1/Gestation) + I(Predation^0.5) + I(Exposure^0.5) + I(Danger^0.5),data = mammals2)
summary(model2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt) + I(1/BrainWt) + I(1/LifeSpan) + I(1/Gestation) + I(Predation^0.5) + I(Exposure^0.5) + I(Danger^0.5),data = mammals2.1)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt) + I(1/BrainWt) + I(1/LifeSpan) + I(1/Gestation) + I(1/Predation) + I(1/Exposure^0.5) + I(1/Danger^0.5),data = mammals2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.5) + I(1/BrainWt^5) + I(LifeSpan^0.5) + I(Gestation) + I(Predation^0.1) + I(Exposure^1) + I(Danger),data = mammals2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.5) + I(1/BrainWt^5) + I(1/LifeSpan^100) + I(Gestation) + I(Predation^0.1) + I(Exposure^1) + I(Danger),data = mammals2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.5) + I(1/BrainWt^5) + I(1/LifeSpan^10) + I(Gestation) + I(Predation^0.1) + I(Exposure^1) + I(Danger),data = mammals2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.5) + I(1/BrainWt^5) + I(LifeSpan^0.001) + I(Gestation) + I(Predation^0.1) + I(Exposure^1) + I(Danger),data = mammals2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.5) + I(1/BrainWt^5) + I(-exp(LifeSpan^0.5)) + I(Gestation) + I(Predation^0.1) + I(Exposure^1) + I(Danger),data = mammals2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.5) + I(1/BrainWt^5) + I(log(LifeSpan)) + I(Gestation) + I(Predation^0.1) + I(Exposure^1) + I(Danger),data = mammals2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.5) + I(1/BrainWt^5) + I(log(LifeSpan^0.1)) + I(Gestation) + I(Predation^0.1) + I(Exposure^1) + I(Danger),data = mammals2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.5) + I(1/BrainWt^5) + I(log(LifeSpan^0.1)) + I(Gestation) + I(Predation^0.1) + I(Exposure^0.1) + I(Danger),data = mammals2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.05) + I(1/BrainWt^5) + I(log(LifeSpan^0.1)) + I(Gestation) + I(Predation^0.1) + I(Exposure^0.1) + I(Danger),data = mammals2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(log(LifeSpan^0.1)) + I(Exposure^0.1) + I(Danger),data = mammals2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(log(LifeSpan)) + I(Exposure^0.1) + I(Danger),data = mammals2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(log(1/LifeSpan)) + I(Exposure^0.1) + I(Danger),data = mammals2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(log1p(1/LifeSpan)) + I(Exposure^0.1) + I(Danger),data = mammals2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(log(10/LifeSpan)) + I(Exposure^0.1) + I(Danger),data = mammals2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(log(LifeSpan)) + I(Exposure^0.1) + I(Danger),data = mammals2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(-log(LifeSpan)) + I(Exposure^0.1) + I(Danger),data = mammals2)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.5) + I(1/BrainWt^5) + I(log(LifeSpan^0.1)) + I(Gestation) + I(Predation) + I(Exposure) + I(Danger), data = mammals2.1)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.5) + I(1/BrainWt^5) + I(log(LifeSpan)) + I(Gestation) + I(Predation) + I(Exposure) + I(Danger), data = mammals2.1)
summary(modelbonus)
plot(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.5) + I(1/BrainWt^5) + I(log(LifeSpan)) + I(Gestation) + I(Predation) + I(Danger), data = mammals2.1)
summary(modelbonus)
plot(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.5) + I(1/BrainWt^5) + I(Gestation) + I(Predation) + I(Danger), data = mammals2.1)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^5) + I(1/BrainWt^5) + I(log(LifeSpan)) + I(Gestation) + I(Predation) + I(Danger), data = mammals2.1)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.1) + I(1/BrainWt^5) + I(log(LifeSpan)) + I(Gestation) + I(Predation) + I(Danger), data = mammals2.1)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.2) + I(1/BrainWt^5) + I(log(LifeSpan)) + I(Gestation) + I(Predation) + I(Danger), data = mammals2.1)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.2) + I(1/BrainWt^5) + I(1、LifeSpan)) + I(Gestation) + I(Predation) + I(Danger), data = mammals2.1)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.2) + I(1/BrainWt^5) + I(1/LifeSpan)) + I(Gestation) + I(Predation) + I(Danger), data = mammals2.1)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.2) + I(1/BrainWt^5) + I(1/LifeSpan) + I(Gestation) + I(Predation) + I(Danger), data = mammals2.1)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.2) + I(1/BrainWt^5) + I(log1p(LifeSpan) + I(Gestation) + I(Predation) + I(Danger), data = mammals2.1)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.2) + I(1/BrainWt^5) + I(log1p(LifeSpan)) + I(Gestation) + I(Predation) + I(Danger), data = mammals2.1)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.2) + I(1/BrainWt^5) + I(log(LifeSpan)) + I(Gestation) + I(Predation) + I(Danger), data = mammals2.1)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^5) + I(1/BrainWt^5) + I(log(LifeSpan)) + I(Gestation) + I(Predation) + I(Danger), data = mammals2.1)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.5) + I(1/BrainWt^5) + I(log(LifeSpan)) + I(Gestation) + I(Predation) + I(Danger), data = mammals2.1)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.3) + I(1/BrainWt^5) + I(log(LifeSpan)) + I(Gestation) + I(Predation) + I(Danger), data = mammals2.1)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(1/BodyWt^0.05) + I(1/BrainWt^5) + I(log(LifeSpan)) + I(Gestation) + I(Predation) + I(Danger), data = mammals2.1)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(BodyWt^-0.2) + I(1/BrainWt^5) + I(log(LifeSpan)) + I(Gestation) + I(Predation) + I(Danger), data = mammals2.1)
summary(modelbonus)
modelbonus <- lm(TotalSleep ~ I(BodyWt^-0.2) + I(BrainWt^-5) + I(log(LifeSpan)) + I(Gestation) + Predation + Danger, data = mammals2.1)
summary(modelbonus)
plot(modelbonus)
modelbonus <- lm(TotalSleep ~ I(BodyWt^-0.2) + I(BrainWt^-5) + I(log(LifeSpan)) + I(Gestation) + Predation + Danger, data = mammals2)
summary(modelbonus)
plot(modelbonus)
modelbonus <- lm(TotalSleep ~ I(BodyWt^-0.2) + I(BrainWt^-5) + I(log(LifeSpan)) + I(Gestation) + Predation + Danger, data = mammals2.1)
summary(modelbonus)
plot(modelbonus)
savehistory('hw5-codedraft')
savehistory('hw5-codedraft.R')
